config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/book_upload', to: 'books#upload'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def upload
    file = params[:pdf_file].tempfile
    reader = PDF::Reader.new(file)

    puts reader.info

    text_full = read_pdf_pages(reader)
    # TODO count the words
    # eliminate duplicates
    # eliminiate common words
    # translate words
    # write to csv
    # give csv download link to individuals
    # change front-end to send javascript post
    # change backend to send json reply
    # allow new csv to be downloaded, json reply lets that happen
    # delete csv
    raise
    file.unlink
  end

  def read_pdf_pages(reader)
    # Refactor this to eliminate common words here, so that common words are eliminated in smaller chunks than one massive memory hogging file
    full_text = ""
    reader.pages.each do |page|
      full_text += (" " + page.text)
    end
    full_text
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnkiDeckMaker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container d-flex align-items-center justify-content-center flex-column">
  <h1>Anki Deck Maker</h1>
  <div>
    <%= form_tag book_upload_path, multipart: true do %>
      <%= file_field_tag :pdf_file %>
      <%= submit_tag "Upload" %>
    </div>
  <% end %>
</div>